name: ci
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Restore
        run: dotnet restore ./src/Orders.Api/Orders.Api.csproj
      - name: Build
        run: dotnet build ./src/Orders.Api/Orders.Api.csproj --configuration Release --no-restore
      - name: Test
        run: echo "(Add tests)"
      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: orders-api:ci
